# Generated by Django 5.0.7 on 2024-07-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointment", "0004_alter_appointment_appointment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="appointment_types",
            field=models.IntegerField(
                choices=[("1", "Offline"), ("2", "Online")], default="Pending"
            ),
        ),
    ]
