# Generated by Django 5.0.7 on 2024-07-17 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctor", "0003_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="doctor.doctor"
            ),
        ),
    ]
